const { boot, baseState, keyOf } = require("./helpers");
module.exports = async T => {
  const st = baseState(); st.days[keyOf(-1)] = { h: {}, s: {}, water: 0, meals: [{ t: 1, n: "Peito de frango grelhado", g: 150, k: 239, p: 48, m: "Almoço" }, { t: 2, n: "Arroz branco cozido", g: 150, k: 192, p: 4, m: "Almoço" }] };
  const a = await boot({ state: st }), ev = a.ev, ptr = (el, type, x, y) => { const e = new a.w.Event(type, { bubbles: true }); e.clientX = x; e.clientY = y; e.pointerId = 1; el.dispatchEvent(e); };
  ev('go("comer")'); const v = () => a.q("#v-comer");
  T.ok(v().querySelectorAll(".meal").length === 5, "5 seções de refeição");
  T.ok(!v().querySelector("#foodlist") && !/Tabela de alimentos/.test(v().textContent), "lista completa de alimentos não aparece");
  T.ok(/Feijão carioca/.test(v().querySelectorAll(".meal")[1].textContent) && !/Café sem açúcar/.test(v().querySelectorAll(".meal")[1].textContent), "sugestões próprias do almoço");
  T.ok(!/Pico Glic|Almoço Padrão|Antigravity/.test(v().textContent), "sem o alerta glicêmico falso nem o almoço padrão fixo");
  const rep = v().querySelector("[data-act=meal-repeat][data-m='Almoço']"); T.ok(rep && /2 itens/.test(rep.textContent), "oferece repetir o almoço de ontem (2 itens)");
  rep.click(); T.ok(ev("D(today()).meals.length") === 2 && ev("D(today()).meals[0].m") === "Almoço", "repetir copia os itens para hoje");
  T.ok(!v().querySelector("[data-act=meal-repeat][data-m='Almoço']"), "botão some depois de usar");
  v().querySelector("[data-act=fiber-add][data-g='5']").click(); v().querySelector("[data-act=fiber-add][data-g='5']").click(); T.ok(ev("D(today()).fiber") === 10, "fibra +5 +5 = 10 g");
  for (let i = 0; i < 3; i++) v().querySelector("[data-act=fiber-add][data-g='-5']").click(); T.ok(ev("D(today()).fiber") === 0, "fibra nunca fica negativa");
  v().querySelectorAll(".meal")[0].querySelector("[data-act=food]").click(); T.ok(a.q("#favbtn") && /Café da manhã/.test(a.q(".sheet").textContent), "chip abre a folha com a refeição certa");
  a.q("#favbtn").click(); T.ok(ev("S.favs['Café da manhã'].length") === 1, "favoritou");
  a.q("[data-act=food-add]").click(); T.ok(/Favoritos/.test(v().querySelectorAll(".meal")[0].textContent), "favorito aparece na seção");
  v().querySelector("[data-act=find]").click(); T.ok(/Digite o nome/.test(a.q("#foodlist").textContent), "busca abre vazia");
  const q = a.q("#q"); q.value = "ovo"; q.dispatchEvent(new a.w.Event("input", { bubbles: true })); T.ok(a.qa("#foodlist .food").length > 0, "digitar mostra resultados"); ev("closeSheet()");
  const n0 = ev("D(today()).meals.length"), row = a.q(".swipe-in"); Object.defineProperty(row, "offsetWidth", { value: 300 });
  ptr(row, "pointerdown", 200, 10); ptr(row, "pointermove", 170, 12); ptr(row, "pointerup", 170, 12); T.ok(ev("D(today()).meals.length") === n0, "arrasto curto não exclui");
  ptr(row, "pointerdown", 250, 10); ptr(row, "pointermove", 180, 12); ptr(row, "pointermove", 90, 12); ptr(row, "pointerup", 90, 12);
  await a.wait(300); T.ok(ev("D(today()).meals.length") === n0 - 1, "arrastar para o lado exclui");
  T.ok(a.q("#toast").classList.contains("act"), "toast oferece desfazer"); a.q("#toast").click(); T.ok(ev("D(today()).meals.length") === n0, "desfazer restaura");
  const r2 = a.qa(".swipe-in")[0]; ptr(r2, "pointerdown", 200, 10); ptr(r2, "pointermove", 203, 60); ptr(r2, "pointermove", 100, 70); ptr(r2, "pointerup", 100, 70); T.ok(ev("D(today()).meals.length") === n0, "gesto vertical é rolagem, não exclui");
  T.ok(!a.errors.length, "sem erros de script"); a.close();
};
